# Pipeline de Seguridad Unificado
name: Pipeline Unificado DevSecOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  devsecops-flow:
    name: Build and Security Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del C?digo Fuente
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Ejecutar Gitleaks SAST
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: detect --verbose

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Construir Imagen Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: lromerob/devsecops-app:latest

    - name: Escanear Contenedor con Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'lromerob/devsecops-app:latest'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
